[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.60"
anyhow = "1.0.83"
graph_builder = "0.4.0"
futures = "0.3.30"
rand_core = { version = "0.6.4", features = ["getrandom"] }



